FROM tomcat:11-jdk21

RUN rm -rf /usr/local/tomcat/webapps/ROOT

COPY LibraryManagement.war /usr/local/tomcat/webapps/ROOT.war

CMD ["sh", "-c", "sed -i \"s/port=\\\"8080\\\"/port=\\\"${PORT:-8080}\\\"/\" /usr/local/tomcat/conf/server.xml && catalina.sh run"]